version: '3'

services:
  frontend.dev:
    container_name: frontend.dev
    image: frontend:dev
    build: 
      context: ./frontend
      dockerfile: ../dockerfiles/frontend.dev.dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 4200:4200
    command: sleep infinity

  backend.dev:
    container_name: backend.dev
    depends_on: 
      - mongo
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    working_dir: /app
    volumes:
      - './backend:/app'
    ports:
      - 5000:5000
      - 5001:5001
    command: sleep infinity
  
  mongo-express:
    image: mongo-express
    depends_on: 
      - mongo
    ports:
      - 8081:8081

  mongo:
    image: mongo

