version: '3'

services:
  frontend.dev:
    container_name: frontend.dev
    image: frontend:dev
    build: 
      context: ./frontend
      dockerfile: ../dockerfiles/frontend.dev.dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 4200:4200
  backend.dev:
    container_name: backend.dev
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    working_dir: /app
    volumes:
      - './backend:/app'
      - '/app/Backend.DataLayer/bin/'
      - '/app/Backend.DataLayer/obj/'
      - '/app/Backend.DataLayer.MongoDB/bin/'
      - '/app/Backend.DataLayer.MongoDB/obj/'
      - '/app/Backend.WebApi/bin/'
      - '/app/Backend.WebApi/obj/'
    ports:
      - 5000:5000
      - 5001:5001
    command: /bin/bash -c ./watch.sh