version: '3'

services:
  frontend:
    container_name: frontend
    depends_on: 
      - backend
    image: frontend
    build: 
      context: ./frontend
      dockerfile: ../dockerfiles/frontend.dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 4200:4200
    command: npm start

  backend:
    container_name: backend
    depends_on: 
      - mongo
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    working_dir: /app
    volumes:
      - './backend:/app'
    ports:
      - 5000:5000
      - 5001:5001
    command: dotnet run --project Backend.WebApi
    restart: always 

  backend.prod:
    container_name: backend.prod
    depends_on:
      - mongo
    build: 
      context: .
      dockerfile: dockerfiles/backend.dockerfile
    restart: always 

  frontend.prod:
    container_name: frontend.prod
    depends_on:
      - backend.prod
    build: 
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - 8080:80
    restart: always 
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on: 
      - mongo
    ports:
      - 8081:8081

  mongo:
    container_name: mongo
    image: mongo
    restart: always 

